version: '3.7'

services:

  deezer-application:
    image: mehrdadkhah/php7
    container_name: deezer-application
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    links:
      - deezer-database
    ports:
      - 8787:8080
    volumes:
      - .:/var/www
      - ./logs:/var/www/logs
    networks:
      - default

  deezer-database:
    image: mysql:latest
    container_name: deezer-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deezer
    ports:
      - "3307:3306"
    volumes:
      - ./infra:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  logs:
    driver: local
