version: '3.7'

services:
  deezer:
    image: php:7-alpine
    container_name: deezer
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - .:/var/www
      - logs:/var/www/logs
    networks:
      - dbnetwork

  database:
    image: mysql:latest
    container_name: deezer-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'deezer'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - database:/var/lib/mysql:rw
      - database:/docker-entrypoint-initdb.d/
    networks:
      - dbnetwork

volumes:
  logs:
    driver: local
  database:
    driver: local

networks:
  dbnetwork:

