version: '3.7'

volumes:
    logs:
        driver: local

services:
    deezer:
        image: php:7-alpine
        container_name: deezer
        working_dir: /var/www
        command: php -S 0.0.0.0:8787 -t /public
        environment:
            docker: "true"
        ports:
            - 8787:8080
        volumes:
            - .:/var/www
            - ../src:/var/www/src
            - ../logs:/var/www/logs
